# Generated by Django 3.0.8 on 2021-02-05 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
