# Generated by Django 3.0.8 on 2021-02-12 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0005_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.TextField(default='Georgia'),
        ),
    ]
